# Generated by Django 3.1.3 on 2020-11-26 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Exchange', max_length=60)),
                ('index', models.CharField(db_column='INDEX', max_length=5)),
            ],
            options={
                'db_table': 'Exchange',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_code', models.IntegerField(db_column='Industry_code')),
                ('industry', models.CharField(db_column='Industry', max_length=50)),
            ],
            options={
                'db_table': 'Industry',
            },
        ),
        migrations.CreateModel(
            name='StatementEntries',
            fields=[
                ('entry_code', models.IntegerField(db_column='Entry Code', primary_key=True, serialize=False)),
                ('statement_title', models.CharField(db_column='Statement Title', max_length=25)),
            ],
            options={
                'db_table': 'Statement',
            },
        ),
        migrations.CreateModel(
            name='ItemSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.IntegerField(db_column='Item Code')),
                ('item_order', models.IntegerField(db_column='Order')),
                ('item_description', models.CharField(db_column='Description', max_length=255)),
                ('item_properties', models.CharField(db_column='Properties', max_length=255)),
                ('item_title', models.CharField(db_column='Title', max_length=255)),
                ('entry_code', models.ForeignKey(db_column='Statement Code', on_delete=django.db.models.deletion.CASCADE, to='firstPage.statemententries')),
            ],
            options={
                'db_table': 'Item',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_column='Ticker', max_length=10)),
                ('name', models.CharField(db_column='Name', max_length=60)),
                ('industry', models.ForeignKey(blank=True, db_column='Industry CODE', null=True, on_delete=django.db.models.deletion.CASCADE, to='firstPage.industry')),
            ],
            options={
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_column='Date')),
                ('close', models.FloatField(db_column='Close')),
                ('volume', models.IntegerField(db_column='Volume')),
                ('seven_days_MA', models.FloatField(db_column='7 day MA')),
                ('seven_days_STD', models.FloatField(db_column='7 day STD')),
                ('fourteen_days_MA', models.FloatField(db_column='14 days MA')),
                ('twenty_one_days_MA', models.FloatField(db_column='21 days MA')),
                ('ticker', models.ForeignKey(db_column='Ticker', on_delete=django.db.models.deletion.CASCADE, to='firstPage.company')),
            ],
            options={
                'db_table': 'Stock',
                'unique_together': {('ticker', 'day')},
            },
        ),
        migrations.CreateModel(
            name='ItemFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_column='Year')),
                ('value', models.BigIntegerField(db_column='Value')),
                ('item_code', models.ForeignKey(db_column='Item Code', on_delete=django.db.models.deletion.CASCADE, to='firstPage.itemsetting')),
                ('ticker', models.ForeignKey(db_column='Ticker', on_delete=django.db.models.deletion.CASCADE, to='firstPage.company')),
            ],
            options={
                'db_table': 'Item Fact',
                'unique_together': {('ticker', 'year', 'item_code')},
            },
        ),
        migrations.CreateModel(
            name='IndexInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_column='Date')),
                ('close', models.FloatField(db_column='Close')),
                ('volume', models.IntegerField(db_column='Volume')),
                ('exchange', models.ForeignKey(db_column='Ticker', on_delete=django.db.models.deletion.CASCADE, to='firstPage.exchange')),
            ],
            options={
                'db_table': 'INDEX',
                'unique_together': {('exchange', 'day')},
            },
        ),
    ]
