# Generated by Django 3.1.3 on 2020-11-26 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='exchange',
            field=models.ForeignKey(blank=True, db_column='INDEX', null=True, on_delete=django.db.models.deletion.CASCADE, to='firstPage.exchange'),
        ),
    ]
