# Generated by Django 3.1.3 on 2020-11-27 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0002_company_exchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinfo',
            name='fourteen_days_MA',
        ),
        migrations.RemoveField(
            model_name='stockinfo',
            name='seven_days_MA',
        ),
        migrations.RemoveField(
            model_name='stockinfo',
            name='seven_days_STD',
        ),
        migrations.RemoveField(
            model_name='stockinfo',
            name='twenty_one_days_MA',
        ),
    ]
